### ISSUE TITLE
请问如何获取弹幕接口？

### ISSUE THREAD

**Issue by xuwei0455** [zephyrzoom/pandatv#1]
我现在正在尝试自己架设一个弹幕服务器，想了解一下作者是如何获取到直播平台的弹幕接口的。
是通过抓包分析么？目前我对这块不是很了解，希望能得到你的帮助，谢谢！

**Comment by zephyrzoom** [comment]
我是用wireshark抓包分析的

**Comment by xuwei0455** [comment]
明白了，多谢你的回答，我尝试一下！

**Comment by xuwei0455** [comment]
@zephyrzoom 请问你知道目前的直播平台弹幕服务都是怎么实现的么？

**Comment by zephyrzoom** [comment]
几乎都是连接socket，连上就可以接受弹幕了，只是弹幕格式不同的网站不一样。

**Comment by xuwei0455** [comment]
知道了，多谢！
